qc = ["qsub", "shellpath/bbduk.sh", "-N", "qc_defaultsample"]
merge = ["qsub", "shellpath/bbmerge.sh", "-hold_jid", "qc_defaultsample", "-N", "merge_defaultsample"]
assembly = ["qsub", "shellpath/megahit.sh", "-hold_jid", "qc_defaultsample", "-N", "assembly_defaultsample"]
mapping = ["qsub", "shellpath/bbmap.sh", "-hold_jid", "assembly_defaultsample", "-N", "mapping_defaultsample"]
maxbin = ["qsub", "shellpath/maxbin.sh", "-hold_jid", "mapping_defaultsample", "-N", "binning_defaultsample"]
metabat2 = ["qsub", "shellpath/metabat2.sh", "-hold_jid", "mapping_defaultsample", "-N", "binning_defaultsample"]
metaphlan2 = ["qsub", "shellpath/metaphlan2.sh", "-hold_jid", "merge_defaultsample", "-N", "metaphlan2_defaultsample"]
checkm = ["qsub", "shellpath/checkm.sh", "-hold_jid", "binning_defaultsample", "-N", "binning_defaultsample"]
test = ["echo", "$PWD"]

qsub_list = [qc, merge, assembly, mapping, maxbin, metabat2, metaphlan2, checkm, test]
